name: release

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

env:
  ELIXIR_VERSION: "1.16.2"
  ERLANG_VERSION: "26.2"

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.ERLANG_VERSION }}

      - name: Release to hex.pm
        run: mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
